version: 2
jobs:
  build:
    environment:
      GO111MODULE: "on"
      GOBIN: "/go/bin"
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/alecthomas/kong-hcl
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            unset GOPATH
            go get -v github.com/jstemmer/go-junit-report
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s v1.23.8
            mkdir ~/report
          when: always
      - run:
          name: Test
          command: |
            go test -v ./... 2>&1 | tee report.txt && /go/bin/go-junit-report < report.txt > ~/report/junit.xml
            (cd v2 && go test -v ./... 2>&1 | tee report.txt && /go/bin/go-junit-report < report.txt > ~/report/junit.xml)
      - run:
          name: Lint
          command: |
            unset GOPATH
            ./bin/golangci-lint run
            (cd v2 && ../bin/golangci-lint run)
      - store_test_results:
          path: ~/report
